from breaking_apart.src.breaking_apart import solve, is_vovel


def test_solve():

    TEST_CASES = [(20, "Dertana et alioumatok gorigo te", ["Dertana et aliouma-", 
                                                      "tok gorigo te"]),
            (10, "Megatonitokaturolefetemelotiavoutuloka", ["Megatoni-", 
                                                            "tokaturo-", 
                                                            "lefeteme-", 
                                                            "lotiavou-", 
                                                            "tuloka"]),
            (11, "Fowjopiakultomentekitavota", ["Fowjopia-", 
                                                "kultomente-", 
                                                "kitavota"]),
            (63, "Sed ut perpiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi arcitecto beatae vitae dicta sun expicabo Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciut Neque porro quisquam et qui dolorem ipsum quia dolor sit amet consectetur adipisci velit sed quia non numquam eius modi tempora incidun ut", ["Sed ut perpiciatis unde omnis iste natus error sit voluptatem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "accusantium doloremque laudantium totam rem aperiam eaque ipsa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "quae ab illo inventore veritatis et quasi arcitecto beatae vi-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "tae dicta sun expicabo Nemo enim ipsam voluptatem quia voluptas",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sit aspernatur aut odit aut fugit sed quia consequuntur magni",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "dolores eos qui ratione voluptatem sequi nesciut Neque porro",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "quisquam et qui dolorem ipsum quia dolor sit amet consectetur",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "adipisci velit sed quia non numquam eius modi tempora incidun",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "ut"]),
            (40, "Lorem ipsum dolor sit amet consectetur adipiscin elit sed do eiusmod tempor incididun ut labore et dolore magna aliqua Ut enim ad minim veniam quis notrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sin occaecat cupidatat non roiden sun in culpa qui officia deserut mollit anim id es laborum", ["Lorem ipsum dolor sit amet consectetur",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "adipiscin elit sed do eiusmod tempor in-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "cididun ut labore et dolore magna aliqua",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Ut enim ad minim veniam quis notrud",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "exercitation ullamco laboris nisi ut",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "aliquip ex ea commodo consequat Duis au-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "te irure dolor in reprehenderit in vo-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "luptate velit esse cillum dolore eu fu-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "giat nulla pariatur Excepteur sin occae-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "cat cupidatat non roiden sun in culpa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "qui officia deserut mollit anim id es",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "laborum"]),
            ]
    
    for length, words, expected in TEST_CASES:
        lines = solve(length, words.split())
        assert all([line==expect for line,expect in zip(lines, expected)])

def test_is_vovel():
    assert all([is_vovel(c) == True for c in "aeiou"])
    assert all([is_vovel(c) == True for c in "aeiou".upper()])
    assert all([is_vovel(c) == False for c in "bcdfghjklmnpqrstvwxyz"])
    assert all([is_vovel(c) == False for c in "bcdfghjklmnpqrstvwxyz".upper()])
